MINGW=i586-pc-mingw32
MINGWLIB=/usr/$(MINGW)/sys-root/mingw/lib
CC=$(MINGW)-gcc
LD=$(MINGW)-ld
CXX=$(MINGW)-g++
STRIP=$(MINGW)-strip
WINDRES=$(MINGW)-windres -v
RANLIB=$(MINGW)-ranlib
AR=$(MINGW)-ar

CFLAGS=-Wall 
ONLYCFLAGS=-Wno-pointer-sign
# TODO: uncomment me for release
CFLAGS+=-D_FORTIFY_SOURCE=2 -O2

LDADD=-static-libgcc
.SUFFIXES: .rc .res .res.o

%.o: %.c
	$(CC) $(CFLAGS) $(ONLYCFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

.rc.res.o:
	$(WINDRES) $^ $@
