/* Autogenerated by ./log2array.sh, do NOT edit! */
struct { char *name; int ms; int res; } et_measure[] = {
{ "MultiByteToWideChar/Latin", 288 },
{ "WideCharToMultiByte/Latin", 286 },
{ "HeapAlloc/HeapFree", 773 },
{ 0, 0 }
};
